services:
  onerom-reader:
    build: ./reader
    ports:
      - "8106:5000"
    volumes:
      - ./data:/data:ro
    restart: unless-stopped
    stop_grace_period: 2s

  onerom-writer:
    build: ./writer
    ports:
      - "8107:5000"
    volumes:
      - ./data:/data
      - ./writer/templates:/app/templates
    stop_grace_period: 2s
